version: '2'
services:
  rails:
    image: ph-rails
    build:
      context: .
      dockerfile: ./Dockerfile.rails
    working_dir: /app
    command: /bin/bash ./entrypoint.sh
    # Removing server.pid first so Rails doesn't think there is another server running
    environment:
      - MAILCHIMP_API_KEY
      - MAILCHIMP_LIST_ID
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.7.17
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=ph-dev
